name: 'SensioLabs Security Checker Action'
description: 'The SensioLabs Security Checker is a command line tool that checks if your application uses dependencies with known security vulnerabilities.'
branding:
  icon: 'check-square'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
